docs update

diff --git a/tfh/libexec/tfh/tests/runner b/tfh/libexec/tfh/tests/runner
--- a/tfh/libexec/tfh/tests/runner
+++ b/tfh/libexec/tfh/tests/runner
@@ -3,41 +3,41 @@
 if [ -f ./utils ]; then
     . ./utils
 else
-    echo "Not found: ./utils. Run testrunner from libexec/tfe/tests" 1>&2
+    echo "Not found: ./utils. Run testrunner from libexec/tfh/tests" 1>&2
     exit 1
 fi
 
-if [ -f ../../../bin/tfe ]; then
-    tfe_dir="$(cd ../../../bin && pwd -P)"
-    export PATH="$tfe_dir:$PATH"
+if [ -f ../../../bin/tfh ]; then
+    tfh_dir="$(cd ../../../bin && pwd -P)"
+    export PATH="$tfh_dir:$PATH"
 else
-    echoerr "Path to tfe not found. Run testrunner from libexec/tfe/tests"
+    echoerr "Path to tfh not found. Run testrunner from libexec/tfh/tests"
     exit 1
 fi
 
-if [ -n "$TFE_ORG" ]; then
-    # TFE_ORG may be set but not exported
-    export TFE_ORG
+if [ -n "$TFH_org" ]; then
+    # TFH_org may be set but not exported
+    export TFH_org
 else
-    echoerr "TFE_ORG must be set to run tests"
+    echoerr "TFH_org must be set to run tests"
     exit 1
 fi
 
 # A particular test file was requested
 if [ -n "$1" ]; then
     # We'll cd into the tests directory, so we only want the test file name.
-    tfe_tests="$(basename $1)"
+    tfh_tests="$(basename $1)"
 
-    if [ ! -f "./tests/$tfe_tests" ]; then
+    if [ ! -f "./tests/$tfh_tests" ]; then
         echoerr "Specific test requested but not found:"
-        echoerr "$tfe_tests"
+        echoerr "$tfh_tests"
         exit 1
     fi
 fi
 
-if [ -n "$TFE_TEST_SHELL" ]; then
-    shells="$TFE_TEST_SHELL"
-elif [ -n "$TFE_TEST_ALL_SHELLS" ]; then
+if [ -n "$TFH_TEST_SHELL" ]; then
+    shells="$TFH_TEST_SHELL"
+elif [ -n "$TFH_TEST_ALL_SHELLS" ]; then
     # posh seems broken for sourcing files when run as
     # posh ./tests/test_name
     # When run interatively it fails to have the right return code for
@@ -65,17 +65,17 @@ for shell in $shells; do
     fi
 
     echoerr "Testing with $shell"
-    if [ -z "$tfe_tests" ]; then
-        tfe_tests="$(find . -type f -name '[0-9][0-9]*_test*' ! -path '*/.*' | sort)"
+    if [ -z "$tfh_tests" ]; then
+        tfh_tests="$(find . -type f -name '[0-9][0-9]*_test*' ! -path '*/.*' | sort)"
     fi
 
-    for tfe_test in $tfe_tests; do
+    for tfh_test in $tfh_tests; do
         # busybox is special because it has to be called as `busybox sh`
         if [ "$shell" = busybox ]; then
             shell="busybox sh"
         fi
 
-        if ! $shell "$tfe_test"; then
+        if ! $shell "$tfh_test"; then
             exit 1
         fi
     done
