new, generated client with junonia_web

diff --git a/tfh/bin/tfh b/tfh/bin/tfh
--- a/tfh/bin/tfh
+++ b/tfh/bin/tfh
@@ -24,321 +24,100 @@
 ##
 ## -------------------------------------------------------------------
 
-##
-## Utility function declarations
-##
-
-# Return (print) "$1\n$2\n." if $1 is not empty, "$2\n." if $1 is empty.
-# These "lists" always have an end-of-list marker, ".", if they are not empty.
-# This is to help track empty list values that would otherwise be \n
-# special characters that will get stripped by command substitution.
-
-# Remove specified files
-cleanup () {
-  if [ -n "$1" ]; then
-    echo "$1" | while read f; do
-      echodebug "cleaning up $f"
-      rm "$f" 2>&3
-      if [ 0 -ne $? ]; then
-        echoerr "Error cleaning up $f"
-        echoerr "$f"
-      fi
-    done
-  else
-    echodebug "No file to clean up"
-  fi
-}
-
-
-# Replace quotes and newlines with escape characters to prepare the
-# value for insertion into JSON.
-escape_value () {
-  printf '%s' "$1" | awk '
-  {
-    gsub(/"/,"\\\"")
-    gsub(/\\n/,"\\\\n")
-  }
-  NR == 1 {
-    value_line = $0
-  }
-  NR != 1 {
-    value_line = value_line "\\n" $0
-  }
-  END {
-    printf "%s", value_line
-  }'
-}
-
-tfh_api_call () {
-  # $1: optional integer parameter for number of next-pages to retrieve
-  # $1 or $2 to $#: arguments to provide to curl
-
-  echodebug "tfh_api_call args: $@"
-
-	if ! [ "$1" -eq "$1" ] >/dev/null 2>&1; then
-    npages="10000"
-  else
-    npages="$1"
-    shift
-	fi
-
-  echodebug "npages: $npages"
-  echodebug "curl args: $@"
- 
-  if [ "$npages" -lt 1 ]; then
-    return 0
-  fi
-
-  case $curl_token_src in
-    curlrc)
-      echovvv "curl --header \"Content-Type: application/vnd.api+json\"" >&2
-      echovvv "     --config \"$curlrc\"" >&2
-      echovvv "     $*" >&2
-
-      resp="$(curl $curl_silent -w '\nhttp_code: %{http_code}\n' \
-                   --header "Content-Type: application/vnd.api+json" \
-                   --config "$curlrc" \
-                   $@)"
-      ;;
-    token)
-      echovvv "curl --header \"Content-Type: application/vnd.api+json\"" >&2
-      echovvv "     --header \"Authorization: Bearer \$TFH_token\"" >&2
-      echovvv "     $*" >&2
-
-      resp="$(curl $curl_silent -w '\nhttp_code: %{http_code}\n' \
-                   --header "Content-Type: application/vnd.api+json" \
-                   --header "Authorization: Bearer $token" \
-                   $@)"
-      ;;
-  esac
-
-  resp_body="$(printf '%s' "$resp" | awk '!/^http_code/; /^http_code/{next}')"
-  resp_code="$(printf '%s' "$resp" | awk '!/^http_code/{next} /^http_code/{print $2}')"
-
-  echodebug "API request http code: $resp_code. Response:"
-  echodebug_raw "$resp_body"
-
-  case "$resp_code" in
-    2*)
-      printf "%s" "$resp_body"
-
-      next_page="$(printf "%s" "$resp_body" | \
-                   jq -r '.meta.pagination."next-page"' 2>&3)"
-
-      if [ -n "$next_page" ] && [ "$next_page" != null ] &&
-         ! [ "$npages" -le 1 ]; then
-        echodebug "next page: $next_page"
-        echodebug "npages: $npages"
-        next_link="$(printf "%s" "$resp_body" | jq -r '.links.next')"
-        echodebug "next link: $next_link"
-        tfh_api_call $((--npages)) "$next_link"
-      fi
-      ;;
-    4*|5*)
-      echoerr "API request failed."
-      echoerr_raw "HTTP status code: $resp_code"
-      if jsonapi_err="$(echo "$resp_body" | jq -r '
-        def leaf_print(o):
-          o.indent as $i |
-          $i + "  " as $ni |
-          o.errors as $e |
-          $e | keys[] as $k |
-            (select(($e[$k] | type) != "array" and ($e[$k] | type) != "object") |
-              "\($k): \($e[$k])"),
-            (select(($e[$k] | type) == "object") |
-              "\($k):",
-              "\(leaf_print({"errors": $e[$k], "indent": $ni}))"),
-            (select(($e[$k] | type) == "array") |
-              "\($k):",
-              "\(leaf_print({"errors": $e[$k], "indent": $ni}))");
-
-        leaf_print({"errors": .errors[], "indent": "  "})')"; then
-        echoerr_raw "JSON-API details:"
-        echoerr_raw "$jsonapi_err"
-      else
-        echoerr "Response:"
-        echoerr_raw "$resp_body"
-      fi
-
-      return 1
-      ;;
-    *)
-      echoerr "Unable to complete API request."
-      echoerr "HTTP status code: $resp_code."
-      echoerr "Response:"
-      echoerr "$resp_body"
-      return 1
-      ;;
-  esac
-}
-
-# Check the version of terraform in use. Commands can use this
-# to verify that their use of Terraform will go as expected.
-tf_version_required () {
-  if [ $# -ne 3 ]; then
-    echoerr "Unable to check the version of Terraform. This is a bug."
-    exit 1
-  fi
-
-  # Verify the terraform command is present
-  if [ -z "$(command -v terraform)" ]; then
-    echoerr "The terraform command must be installed"
-    exit 1
-  fi
-
-  # Test the version numbers provided in the output with the three arguments
-  if ! terraform -version | awk -v major=$1 -v minor=$2 -v micro=$3 -F. '
-    NR==1 {
-      sub(/[^[0-9]*/, "", $1)
-      if($1 > major) exit 0
-      if($1 == major && $2 > minor) exit 0
-      if($1 == major && $2 == minor && $3 >= micro) exit 0
-      exit 1
-    }'
-  then
-    echoerr "This operation requires at least Terraform $1.$2.$3"
-    exit 1
-  fi
-}
-
-check_required () {
-  if [ 0 -eq $# ]; then
-    check_for="org ws token address"
-  else
-    check_for="$*"
-  fi
-
-  missing=0
-  for i in $check_for; do
-    case "$i" in
-      org)
-        if [ -z "$org" ]; then
-          missing=1
-          echoerr 'TFE organization required.'
-          echoerr 'Set with $TFH_org or use -org'
-          echoerr
-        fi
-      ;;
-      ws)
-        if [ -z "$ws" ]; then
-          missing=1
-          echoerr 'TFE workspace name required.'
-          echoerr 'Set with $TFH_name or use -name, and optionally -prefix'
-          echoerr
-        fi
-      ;;
-      token)
-        if [ "$curl_token_src" = none ]; then
-          missing=1
-          echoerr 'TFE API token required.'
-          echoerr 'Set with `tfh curl-config`,  $TFH_token, or -token'
-          echoerr
-        fi
-      ;;
-      address)
-        # This really shouldn't happen. Someone would have to
-        # explicitly pass in an empty string to the command line
-        # argument.
-        if [ -z "$address" ]; then
-          missing=1
-          echoerr 'TFE hostname required.'
-          echoerr 'Set with -hostname or $TFH_hostname'
-          echoerr
-        fi
-      ;;
-    esac
-  done
-  return $missing
-}
 
 tfh_junonia_filter () {
   readonly TFH_DEFAULT_CURLRC="$JUNONIA_CONFIGDIR/curlrc"
 
-  readonly org="$1"
-  readonly name="$2"
-  readonly prefix="$3"
-  readonly token="$4"
-  readonly curlrc="${5:-"$TFH_DEFAULT_CURLRC"}"
-  readonly hostname="$6"
+  readonly hostname="$1"
+  readonly oauth="$2"
+  readonly curlrc="${3:-"$TFH_DEFAULT_CURLRC"}"
 
   # Waterfall verbosity levels down
-  readonly vvverbose="$9"
-  readonly vverbose="${8:-$vvverbose}"
-  readonly verbose="${7:-$vverbose}"
+  readonly vvverbose="${4}"
+  readonly vverbose="${5:-$vvverbose}"
+  readonly verbose="${6:-$vverbose}"
 
-  readonly address="https://$hostname"
-  readonly ws="$prefix$name"
+  echov "hostname:          $hostname"
+  echov "oauth:             $oauth"
+  echov "curlrc:            $curlrc"
+  echov "verbose:           $verbose"
+  echov "vverbose:          $vverbose"
+  echov "vvverbose:         $vvverbose"
 
-  echov "org:       $org"
-  echov "prefix:    $prefix"
-  echov "workspace: $name"
-  echov "hostname:  $hostname"
-  echov "address:   $address"
-  echov "verbose:   $verbose"
-  echov "vverbose:  $vverbose"
-  echov "vvverbose: $vvverbose"
+  if [ -z "$hostname" ]; then
+    echoerr "A hostname is required"
+    return 64 # filter function error code
+  fi
 
-  curl_token_src=
+  JW_ADDL_PARAMS="HOSTNAME=$hostname"
+  JW_CONTENT_TYPE=application/vnd.api+json
+
+  curl_auth_src=
 
   # curlrc argument at the command line takes highest precedence
   if echo "$TFH_CMDLINE" | grep -qE -- '-curlrc'; then
     echodebug "explicit -curlrc"
     if [ -f "$curlrc" ]; then
-      curl_token_src=curlrc
+      curl_auth_src=curlrc
     else
-      curl_token_src=curlrc_not_found
+      curl_auth_src=curlrc_not_found
     fi
   fi
 
-  # token at the command line takes second highest precedence
-  if [ -z "$curl_token_src" ] && [ -n "$token" ] &&
-     echo "$TFH_CMDLINE" | grep -qE -- '-token'; then
-    echodebug "explicit -token"
-    curl_token_src=token
+  # Look for an oauth token
+  if [ -z "$curl_auth_src" ] &&
+     [ -n "$oauth"         ] &&
+     echo "$TFH_CMDLINE" | grep -qE -- '-oauth'; then
+    echodebug "explicit -oauth"
+    curl_auth_src=oauth
   fi
 
-  # curlrc from any source (default included) comes third
-  if [ -z "$curl_token_src" ] && [ -f "$curlrc" ]; then
-    echodebug "curlrc from env and config file"
-    curl_token_src=curlrc
+  # curlrc from any source (default included)
+  if [ -z "$curl_auth_src" ] && [ -f "$curlrc" ]; then
+    echodebug "curlrc from env or config file"
+    curl_auth_src=curlrc
   fi
 
-  # token from the config file or environment var comes last
-  if [ -z "$curl_token_src" ] && [ -n "$token" ]; then
-    echodebug "token from env and config file"
-    curl_token_src=token
+  # oauth from the config file or environment var
+  if [ -z "$curl_auth_src" ] && [ -n "$oauth" ]; then
+    echodebug "oauth token from env or config file"
+    curl_auth_src=oauth
   fi
 
-  if [ -z "$curl_token_src" ]; then
-    curl_token_src=none
+  if [ -z "$curl_auth_src" ]; then
+    curl_auth_src=none
   fi
 
-  if [ -z "$token" ]; then
-    token_status="empty"
+  if [ -z "$oauth" ]; then
+    oauth_status="empty"
   else
-    token_status="not empty"
+    oauth_status="not empty"
   fi
 
-  case $curl_token_src in
+  case $curl_auth_src in
     curlrc)
-      echov "token:     $token_status, unused"
+      echov "oauth:     $oauth_status, unused"
       echov "curlrc:    $curlrc"
+      JW_CURLRC="$curlrc"
       ;;
-    token)
-      echov "token:     $token_status"
+    oauth)
+      echov "oauth:     $oauth_status"
       echov "curlrc:    $curlrc, unused"
+      JW_OAUTH="$oauth"
       ;;
     curlrc_not_found)
-      echov "token:     $token_status, unused"
+      echov "oauth:     $oauth_status, unused"
       echov "curlrc:    $curlrc specified but not found"
       ;;
     none)
-      echov "token:     empty"
+      echov "oauth:     $oauth_status, unused"
       echov "curlrc:    $curlrc not found"
       ;;
   esac
 
-  return 9
+  junonia_auth_config
+
+  return 6
 }
 
 # This is a compact version of junonia_bootstrap for easy copyhing into user
@@ -365,11 +144,11 @@ junonia_bootstrap () {
 # Top level invocation of the command.
 tfh () {
   $0 help
-  return 1
+  exit 1
 }
 
 tfh_version () {
-  echo "0.2.10dev"
+  echo "3.0.0dev"
 }
 
 ##
@@ -389,7 +168,7 @@ tfh_version () {
 # Save the whole command line
 readonly TFH_CMDLINE="$0 $*"
 
-if [ -n "$TF_LOG" ]; then
+if [ -n "$TFH_DEBUG" ]; then
   # Debugging. Print command errors and make them verbose
   tar_verbose=v
   curl_silent=
@@ -405,10 +184,13 @@ fi
 
 junonia_bootstrap
 
+JUNONIA_WRAP=150
+JUNONIA_COL1=50
+JUNONIA_COL2=100
+
 . "$JUNONIA_PATH"/lib/tfh/junonia
 
 echodebug "$PWD"
 echodebug "$0 $*"
 
 junonia_run "$@"
-exit $?
